name: pytorch_sac
channels:
  - defaults
dependencies:
  - python=3.7.6
  - pytorch
  - jupyter
  - cudatoolkit=11.0
  - absl-py
  - pyparsing
  - pip:
    - termcolor
    - git+https://github.com/deepmind/dm_control.git
    - git+https://github.com/denisyarats/dmc2gym.git
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - git+https://github.com/facebookresearch/hydra@0.11_branch.git
